apiVersion: v1
kind: Service
metadata:
  name: echo-app-service
  labels:
    app: echo-app
spec:
  type: ClusterIP
  selector:
    app: echo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
