apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - local.example.com
    secretName: tls-secret
  rules:
  - host: local.example.com
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: info-service
            port:
              number: 80
      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: echo-app-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: info-service
            port:
              number: 80
