apiVersion: v1
kind: Service
metadata:
  name: info-service
  labels:
    app: info-service
    tier: backend
spec:
  type: NodePort
  selector:
    app: info-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5050
    nodePort: 30080
