apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "info-service.fullname" . }}-env
  labels:
    {{- include "info-service.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  LOG_LEVEL: {{ .Values.logLevel | default "INFO" | quote }}
  {{- if .Values.vault.enabled }}
  VAULT_ENABLED: "true"
  VAULT_SECRETS_PATH: {{ .Values.vault.secretsPath | default "/vault/secrets" | quote }}
  {{- else }}
  VAULT_ENABLED: "false"
  {{- end }}
  CONFIG_PATH: "/config/config.json"
  VISITS_FILE: {{ .Values.visitsFile | default "/data/visits.txt" | quote }}
  