apiVersion: v1
kind: Service
metadata:
  name: {{ include "info-service.fullname" . }}-preview
  labels:
    {{- include "info-service.labels" . | nindent 4 }}
    role: preview
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "info-service.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ add .Values.service.nodePort 1 }}
    {{- end }}
