replicaCount: 2

image:
  repository: scruffyscarf/info-service-python
  tag: monitoring
  pullPolicy: Always

environment: monitoring-test
debug: true
logLevel: "DEBUG"

service:
  type: ClusterIP
  port: 80
  targetPort: 5050

persistence:
  enabled: true
  size: 100Mi

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

env:
  APP_NAME: "info-service-monitoring"
  DEBUG: "true"

monitoring:
  enabled: true
