---
- name: Provision web servers
  hosts: webservers
  become: true

  roles:
    - role: common
      tags:
        - common
        - system
    - role: docker
      tags:
        - docker
        - containers
