apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: info-service
  namespace: argocd
spec:
  description: Info Service Application Project
  
  sourceRepos:
    - 'https://github.com/scruffyscarf/DevOps-Core-Course.git'
  
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceBlacklist:
    - group: ''
      kind: 'ResourceQuota'
    - group: ''
      kind: 'LimitRange'
