name: Ansible Deployment Python App

on:
  push:
    branches: [ main, master, lab06 ]
    paths:
      - 'ansible/vars/app_bonus.yml'
      - 'ansible/playbooks/deploy_bonus.yml'
      - 'ansible/roles/web_app/tasks/**'
      - 'ansible/roles/web_app/templates/docker-compose.yml.j2'
      - '.github/workflows/ansible-deploy-bonus.yml'
  pull_request:
    branches: [ main, master, lab06 ]
    paths:
      - 'ansible/vars/app_bonus.yml'
      - 'ansible/playbooks/deploy_bonus.yml'

env:
  ANSIBLE_CONFIG: ansible/ansible.cfg
  ANSIBLE_ROLES_PATH: ansible/roles
  ANSIBLE_HOST_KEY_CHECKING: False
  ANSIBLE_SSH_ARGS: '-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  VM_HOST: ${{ secrets.VM_HOST }}
  VM_USER: ${{ secrets.VM_USER }}
  APP_NAME: 'devops-go'
  APP_PORT: '8001'

jobs:
  lint:
    name: Lint Python App Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint
          ansible-galaxy collection install community.docker

      - name: Syntax check Go playbook
        run: |
          cd ansible
          ansible-playbook playbooks/deploy_bonus.yml --syntax-check

      - name: Run ansible-lint
        run: |
          cd ansible
          ansible-lint playbooks/deploy_bonus.yml

  deploy:
    name: Deploy Go App
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Setup Ansible Vault
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/vault_pass
          chmod 600 /tmp/vault_pass

      - name: Deploy Bonus
        run: |
          export ANSIBLE_ROLES_PATH="$GITHUB_WORKSPACE/ansible/roles"
          export ANSIBLE_HOST_KEY_CHECKING=False
          
          ansible-playbook playbooks/deploy-bonus.yml --syntax-check\
            --vault-password-file /tmp/vault_pass
